export const data = [
  {
    name: "Concept 1",
    url: "/images/1.jpg",
    description: "Interior Concept 1",
    date: "2023-01-01",
    type: "image/jpg",
  },
  {
    name: "Concept 2",
    url: "/images/2.jpg",
    description: "Interior Concept 2",
    date: "2023-01-01",
    type: "image/jpg",
  },
  {
    name: "Concept 3",
    url: "/images/3.jpg",
    description: "Interior Concept 3",
    date: "2023-01-01",
    type: "image/jpg",
  },
  {
    name: "Concept 4",
    url: "/images/4.jpg",
    description: "Interior Concept 4",
    date: "2023-01-01",
    type: "image/jpg",
  },
  {
    name: "Concept 5",
    url: "/images/5.jpg",
    description: "Interior Concept 5",
    date: "2023-01-01",
    type: "image/jpg",
  },
  {
    name: "Concept 6",
    url: "/images/6.jpg",
    description: "Interior Concept 6",
    date: "2023-01-01",
    type: "image/jpg",
  },
  {
    name: "Concept 7",
    url: "/images/7.jpg",
    description: "Interior Concept 7",
    date: "2023-01-01",
    type: "image/jpg",
  },
  {
    name: "Concept 8",
    url: "/images/8.jpg",
    description: "Interior Concept 8",
    date: "2023-01-01",
    type: "image/jpg",
  },
  {
    name: "Concept 9",
    url: "/images/9.jpg",
    description: "Interior Concept 9",
    date: "2023-01-01",
    type: "image/jpg",
  },
];
